### ISSUE TITLE
Conversion of JS primitives on statement creation for subject & predicate

### ISSUE THREAD

**Issue by ckristo** [linkeddata/rdflib.js#115]
Hello,

I noticed that when passing plain JS strings to the $rdf.Statement constructor function (e.g. used by formula.add()), they will automatically be converted to literals, even when they are passed as subject or predicate, e.g.
````js
new $rdf.Statement('#me', 'foaf:name', 'Christoph Kindl');
/* => Statement {
  subject: Literal { value: '#me', lang: undefined, datatype: undefined },
  predicate: Literal { value: 'foaf:name', lang: undefined, datatype: undefined },
  object: 
   Literal {
     value: 'Christoph Kindl',
     lang: undefined,
     datatype: undefined } }
*/
````
Is that behavior intended? As far as I know, RDF does only allow URIs and bnodes for the subject, and URIs for the predicate. I must admit that I would not have expected this behavior. 

BR,

**Comment by timbl** [comment]
Yes, that is the design. Motivations:
- N3 extends RDF to be symmetrical between subject and object, and allow literals as subjects too.   You can say   "3 a :prime ."  There was a plan to retrofit this to RDF but I forget what stage that got to.   The lack of symmetry in RDF was leading to some unnecessary awkwardness.
- N3 allows bnode predicates.
- There is a certain benefit to being able to treat all 4 parts of the quad the same, even iterating over them.

That's the historical reason.

**Comment by ckristo** [comment]
Interesting, I wasn't aware of that, thanks! :-)
BR,
