### ISSUE TITLE
Jade Renamed To Pug

### ISSUE THREAD

**Issue by sible777** [linkeddata/rdflib.js#126]
https://github.com/pugjs/pug/issues/2184

Somebody has a trademark on the name Jade realting to software so, I will be updating the projects dependencies to use pug instead.

**Comment by dmitrizagidulin** [comment]
@sible777 - This lib (rdflib.js) doesn't depend on jade, though, does it?

**Comment by sible777** [comment]
Whoops, I left my comment on the wrong repo! How embarrassing. Thanks for pointint that out. 
This is what happens when you too many tabs open, haha.

**Comment by dmitrizagidulin** [comment]
Haha no worries :)
