### ISSUE TITLE
Reduce preference for application/rdf+xml in favor of text/turtle.

### ISSUE THREAD

**Issue by deiu** [linkeddata/rdflib.js#153]
Currently, when rdflib.js builds the Accept header values, it doesn't set a `q` value for `application/rdf+xml`, which means that by default is interpreted as `q=1`.

I would like to suggest a minor deprecation, by setting `q=0.9` for `application/rdf+xml`, in favor of using `text/turtle` with `q=1`.

I will submit a PR with a fix very soon.

**Comment by akuckartz** [comment]
Which other RDF MIME types are supported? What is or should be their "q"?
