### ISSUE TITLE
Multiple owl:sameAs converted to link:uri

### ISSUE THREAD

**Issue by pasqLisena** [linkeddata/rdflib.js#185]
I have problems in defining multiple `owl:sameAs` links: the first one is correctly mantained, while the others are converted in `link:uri`.

What I expect:
```ttl
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix ent: <http://www.wikidata.org/entity/>.
@prefix link: <http://www.w3.org/2007/ont/link#>.

<http://data.doremus.org/artist/6a3d23e2-3264-3fb4-b1f9-c71b50eed635>
    owl:sameAs
       <http://www.wikidata.org/entity/Q2821467>,
        <http://viaf.org/viaf/121568779>,
        <https://musicbrainz.org/artist/abd51f20-f80d-4114-b139-5b71bc4bbce9>.
```

What I obtain:
```ttl
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix ent: <http://www.wikidata.org/entity/>.
@prefix link: <http://www.w3.org/2007/ont/link#>.

<http://data.doremus.org/artist/6a3d23e2-3264-3fb4-b1f9-c71b50eed635>
    owl:sameAs
       ent:Q2821467;
    link:uri
        "http://viaf.org/viaf/121568779",
        "http://www.wikidata.org/entity/Q2821467",
        "https://musicbrainz.org/artist/abd51f20-f80d-4114-b139-5b71bc4bbce9".
```

My code: 
```js
const $rdf = require('rdflib');
const fs = require('fs');

var OWL = $rdf.Namespace("http://www.w3.org/2002/07/owl#");

var store = $rdf.graph();
var artist = $rdf.sym('http://data.doremus.org/artist/6a3d23e2-3264-3fb4-b1f9-c71b50eed635');

store.add(artist, OWL('sameAs'), $rdf.sym(`http://www.wikidata.org/entity/Q2821467`));
store.add(artist, OWL('sameAs'), $rdf.sym(`http://viaf.org/viaf/121568779`));
store.add(artist, OWL('sameAs'), $rdf.sym(`https://musicbrainz.org/artist/abd51f20-f80d-4114-b139-5b71bc4bbce9`));

$rdf.serialize(undefined, store, 'http://example.org', 'text/turtle', (err, str) => {
  if (err) return console.error(err);

  fs.writeFile('../data/artists.ttl', str, 'utf8');
});
```

**Comment by mrkvon** [comment]
I've experienced this behavior today and I'm frustrated because I don't like nor understand it. Why would rdflib add a predicate we haven't asked for? Is this a bug?

If it is not a bug, can somebody please explain why this is a desired behavior?

**Comment by timbl** [comment]
That’s not a bug, that’s a feature! But it should not be enabled by default.  It’s called smushing, and it involves all the graphs about the same thing being smushed together so that one one node. That is the canonical URI for it. It’s handy for querying ... but it should not be turned on by default. So that’s a bug.

**Comment by timbl** [comment]
...and a bug I thought was fixed a long time ago

**Comment by mrkvon** [comment]
@timbl Thank you for the explanation!

_Some research later:_

It seems that this is a [feature enabled by default](https://github.com/linkeddata/rdflib.js/blob/master/src/store.ts#L192).

To turn it off, one has to provide a first parameter to `$rdf.IndexedFormula` constructor:

```js
import { IndexedFormula, Statement, Namespace } from 'rdfllib';

const store = new IndexedFormula([]); // the first parameter to constructor is features
                                    // which is ['sameAs', 'InverseFunctionalProperty', 'FunctionalProperty'] by default

// and now we have a store with the feature turned off
const owl = new Namespace('http://www.w3.org/2002/07/owl#');
store.add(new Statement(subject, owl('sameAs'), object)); // works without adding link:uri
```
So to resolve this issue, the features should be turned off by default, or documentation improved.
Or perhaps this is already documented, which I've missed, in that case this can be probably closed.

**Comment by mrkvon** [comment]
I tried to update the document with UpdateManager.

On node-solid-server, with the [features in rdflib.js store turned off](https://github.com/linkeddata/rdflib.js/issues/185#issuecomment-595745921), the `link:uri` is still created together with or instead of `owl:sameAs`.

When I send the following request:
```
PATCH https://user.solid.community/public/test/index.ttl
```
```
INSERT DATA { <https://user.solid.community/public/test/index.ttl#example1> <http://www.w3.org/2002/07/owl#sameAs> <https://user.solid.community/public/test/index.ttl#example2 . }
```

The following gets created: `user:example1 owl:sameAs user:example2.` and `user:example2 link:uri user:example1.`.

Seems like it is the `node-solid-server` which decides to add the `link:uri`, isn't it? Where and how to disable this?

:confused:
