### ISSUE TITLE
Cannot parse mimetype 'text/turtle' : octets.decode is not a function

### ISSUE THREAD

**Issue by Spadon** [linkeddata/rdflib.js#208]
Hello,

I am currently trying to parse a turtle file. My code is

```
var ontoStr = fs.readFileSync('./test/ontologies/fipa_crop.ttl');
$rdf.parse(ontoStr, graph, "http://example.com/test", 'text/turtle');
```

I tried with different turtle files, but I always encounter the following error:

> Error trying to parse <http://example.com/test> as text/turtle:
> TypeError: octets.decode is not a function:
> TypeError: octets.decode is not a function
>     at __SinkParser.feed ([...]\node_modules\rdflib\lib\n3parser.js:311:26)

The above code works perfectly with application/ld+json

**Comment by melvincarvalho** [comment]
Thanks for raising this issue.

Do you have the turtle file?

**Comment by Spadon** [comment]
Hi Melvin,
Sure, here it is
[fipa_crop.zip](https://github.com/linkeddata/rdflib.js/files/1527633/fipa_crop.zip)

**Comment by Spadon** [comment]
Hi Melvin,
The content of the turtle file is the following:

```
@prefix fipa: <http://sites.google.com/site/smartappliancesproject/ontologies/fipa#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

fipa:AgentPlatformDescription
  rdf:type owl:Class ;
  rdfs:comment "The class AgentPlatformDescription is part of the FIPA-Nomadic-Application ontology that can be found in [FIPA00023]"^^xsd:string ;
  rdfs:label "Agent Platform description"^^xsd:string ;
.
```

**Comment by melvincarvalho** [comment]
Thanks!

Just eye balling it, I dont often see a semicolon at the end followed by a .

Perhaps try a simpler turtle file?

```turtle
<1> <2> <3> .
```
Something as simple as the above should be valid turtle.

**Comment by Spadon** [comment]
OK thanks. I will try with this representation.

FYI the syntax with semicolons has been produced by [rdftranslator](rdf-translator.appspot.com) from a jsonld file. It seems turtle-valid according to the [recommendation](https://www.w3.org/TR/turtle/#sec-intro).

Best,

Mehdi

**Comment by Spadon** [comment]
My bad, forgot the .toString() after the fs.readFileSync() :/
Now works perfectly.

Kinda odd though, it worked with application/ld+json without any toString needed.

Sorry for that,

Mehdi.

**Comment by melvincarvalho** [comment]
No worries, good luck with your code! :)
