### ISSUE TITLE
npm install broken in 0.16.4

### ISSUE THREAD

**Issue by dduran1967** [linkeddata/rdflib.js#213]
NPM install in 0.16.4 is missing /lib.  

```
> npm install --save rdflib
> ls node_modules/rdflib

README.md     changes.txt   package.json
```

**Comment by melvincarvalho** [comment]
Thanks for reporting this.

Which version of npm are you using?

**Comment by melvincarvalho** [comment]
OK, I can reproduce this

**Comment by melvincarvalho** [comment]
Cant say I know why this happened.  But I have bumped the version and published the package again.

It should now contain the lib directory

**Comment by melvincarvalho** [comment]
Closing, please reopen if there are further issues!
