### ISSUE TITLE
but stil can't figure out what editing protcol it supports.

### ISSUE THREAD

**Issue by rimmartin** [linkeddata/rdflib.js#264]
Hi, using clones from the last few days of node-solid-server, rdflib.js and https://solid.github.io/solid-auth-client/dist/solid-auth-client.bundle.js.

I'm trying to make a quad where it asserts one Container  contains another into the store and then update thru the UpdateManager

```
        const LDP = this.rdf.Namespace('http://www.w3.org/ns/ldp#>');
        let folder = this.rdf.sym('https://roger.localhost:8443/public/');  // NOTE: Ends in a slash
        let childFolder = this.rdf.sym('https://roger.localhost:8443/public/'+path+'/');  // NOTE: Ends in a slash
        let ins = this.store.add(folder, LDP('contains'), childFolder, folder.doc());
        let del = [];
        this.updater.update(del, ins, (uri, ok, message) => {
          if (ok) console.log('contains '+ path);
          else alert(message);
        });

```
where path is "scad-poser" I get "Exception in update: Error: Update: Loaded <https://roger.localhost:8443/public/>but stil can't figure out what editing protcol it supports." alert.   If I list the store with
```
        const LDP = this.rdf.Namespace('http://www.w3.org/ns/ldp#>');
        let folder = this.rdf.sym('https://roger.localhost:8443/public/');  // NOTE: Ends in a slash
        this.fetcher.load(folder).then((result) => {
         	let files = this.store.any(folder, LDP('contains'));
		callback(null, files);
        	/*files.forEach(file) {
        	    callback(' contains ' + file);
            }*/
        }).catch((error) => {
          console.log('There has been a problem with your fetch operation: ', error.message);
        });
```
it shows it is in the store
```
Object { termType: "NamedNode", value: "https://roger.localhost:8443/public/scad-poser/" }
```

Simply I made a bad assertion and Statement from the store.add?
Or is there some setting to get the edit protocol defined in the UpdateManager?
I see it must be at the secondTry:
https://github.com/linkeddata/rdflib.js/pull/241

**Comment by rimmartin** [comment]
```
const LDP = this.rdf.Namespace('http://www.w3.org/ns/ldp#>');
//needs to be
const LDP = this.rdf.Namespace('http://www.w3.org/ns/ldp#');
```
but no change in outcome

**Comment by rimmartin** [comment]
@JornWildt , I've created an empty container as a child of another container using solid-auth-client https://github.com/solid/solid-auth-client and the Slug example in https://github.com/solid/solid-spec/blob/master/api-rest.md
```
        solid.auth.fetch('https://roger.localhost:8443/public/scad/', {
           method: 'POST', // or 'PUT'
           headers:{
            'Content-Type': 'text/turtle',
	    'Link': '<http://www.w3.org/ns/ldp#BasicContainer>; rel="type"',
            'Slug':  'scad-poser'
	   }
           }).then((res) => {return res;})
        .then((response) => {callback(null);})
        .catch((error) => {callback('Error: '+JSON.stringify(error));});

```
but haven't been able to do it with rdflibjs

**Comment by timbl** [comment]
That error means that the library doesn't have enough information to know what forms of PATCH etc the server accepts, because it hasn't accessed the file yet.   This is fixed in more recent versions as the update function in this case does an automatic  GET first to get that information before doing the PATCH. Should work now.
