### ISSUE TITLE
persistence (IndexedDB)

### ISSUE THREAD

**Issue by alhuber1502** [linkeddata/rdflib.js#267]
Are there any plans to enable client-side (browser) persistence of the store, using IndexedDB, or similar?  Thanks!

**Comment by jeff-zucker** [comment]
Well, I just saw this ... my library [Solid-Rest](https://github.com/solid/solid-rest) does indeed have a BrowserFS plugin which supports Solid pod-like access to indexedDB, localStorage, Native File API, and other forms of in-browser storage.  It's a bit rusty at this point so if you have an interest in using it, feel free to contact me directly on the gitter chat as jeff-zucker or in the forum as jeffz.

**Comment by jeff-zucker** [comment]
P.S. it works transparently with rdflib so one can use rdflib and apps based on it to address the indexedDB storage.
