### ISSUE TITLE
Can't get the http status code on callbacks

### ISSUE THREAD

**Issue by slorber** [linkeddata/rdflib.js#29]
When a callback is fired, the xhr object is not passed, neither the status code.

```
    this.failFetch = function(xhr, status) {
        console.error("failFetch called with",xhr,status);
        this.addStatus(xhr.req, status)
        kb.add(xhr.uri, ns.link('error'), status)
        this.requested[$rdf.uri.docpart(xhr.uri.uri)] = false
        this.fireCallbacks('fail', [xhr.requestedURI, status])
        xhr.abort()
        return xhr
    }
```

The status here is a String usually, like "XHR Error: "

When the fetch failed it would be nice to have a way to get the http status code in the callbacks when calling requestURI

**Comment by timbl** [comment]
Fixed in commit ca77d9ed113f9f0b5f5f8dc0bf97a76d053aaa26
