### ISSUE TITLE
Parsing n-quads throws "callback is not a function" error

### ISSUE THREAD

**Issue by RinkeHoekstra** [linkeddata/rdflib.js#323]
When trying to parse N-Quads (application/n-quads), rdflib throws an error:

`$rdf.parse("<http://ex.com/a> <http://ex.com/b> <http://ex.com/c> <http://ex.com/d> .", $rdf.graph(), "http://ex.com", "application/n-quads");`

The error is:

```
Uncaught TypeError: callback is not a function
    at N3Parser.tripleCallback [as _callback] (rdflib.min.js:25694)
    at N3Parser._readInTopContext (rdflib.min.js:13663)
    at rdflib.min.js:14265
    at N3Lexer._tokenizeToEnd (rdflib.min.js:13291)
    at rdflib.min.js:13529
    at run (rdflib.min.js:17986)
    at runIfPresent (rdflib.min.js:18015)
    at onGlobalMessage (rdflib.min.js:18055)
```

In some cases the model remains empty, but in other cases some triples do get loaded. I haven't been able to track down exactly where this occurs.

**Comment by megoth** [comment]
`$rdf.parse` takes a fifth argument which should be a callback-function. It seems that most of the cases where a missing callback is handled, but some are not.

Have you tried passing a function as the fifth parameter?

**Comment by RinkeHoekstra** [comment]
Thanks for your suggestion. I'll give it a go and will report back here.

**Comment by RinkeHoekstra** [comment]
Works (apologies for the delay in reporting back)
