### ISSUE TITLE
Fetcher.putback breaks for contentType JSON-LD

### ISSUE THREAD

**Issue by akashdeep-singh** [linkeddata/rdflib.js#324]
The `putback` method breaks if contentType is `application/ld+json`. This is because it calls the `serialize` function which accepts an optional callback which seems to be required only in case of JSON-LD. Refer the following lines:

https://github.com/linkeddata/rdflib.js/blob/a15d8768d82c452400f11e4d9747a8e43a846db0/src/fetcher.js#L1072

https://github.com/linkeddata/rdflib.js/blob/a15d8768d82c452400f11e4d9747a8e43a846db0/src/serialize.js#L44

**Comment by jeff-zucker** [comment]
Fixed by https://github.com/linkeddata/rdflib.js/commit/a24dc44ef7bb31ce230f1fb96d44b85580ddc311 which encorporates the changes suggested by @akashdeep-singh .
