### ISSUE TITLE
Current browser version doesn't work

### ISSUE THREAD

**Issue by RubenVerborgh** [linkeddata/rdflib.js#334]
Building with `npm run prepare` results in

```
TypeError: "exports" is read-only
```

because we still have old exports.

**Comment by timbl** [comment]
old exports?

**Comment by timbl** [comment]
works for me  on wac-allow branch

**Comment by RubenVerborgh** [comment]
Immediate problem fixed by adjusting Babel config; we might still want #335 though for other reasons.
