### ISSUE TITLE
Release rdflib as version 1.0.0

### ISSUE THREAD

**Issue by megoth** [linkeddata/rdflib.js#336]
@timbl wants us to publish rdflib as v1.0.0, and thinks we should do that at the next opportunity.

**Comment by RubenVerborgh** [comment]
Suggested inclusions:
- https://github.com/linkeddata/rdflib.js/issues/326 (bug)
- https://github.com/linkeddata/rdflib.js/pull/335 (packaging)

Would have loved:
- https://github.com/linkeddata/rdflib.js/issues/329 (Turtle compatibility)
but likely not enough time

**Comment by megoth** [comment]
I've included https://github.com/linkeddata/rdflib.js/issues/326 but not https://github.com/linkeddata/rdflib.js/pull/335 as I think @timbl wants to review it first.

**Comment by RubenVerborgh** [comment]
Ah no :-( Why did this have to go so fast.
Now we might be breaking interface.

**Comment by RubenVerborgh** [comment]
Is it on npm already? If not, let's roll back.
This was too fast.

**Comment by RubenVerborgh** [comment]
This was a big step for rdflib, should've had a beta first.

Let's please think first before we progress further with 1.x releases now.

**Comment by megoth** [comment]
> Ah no :-( Why did this have to go so fast.
> Now we might be breaking interface.

I'm sorry, I was of the impression that the interface was stable and not in need of a beta phase. But I realize I should've asked more around first, my bad =/

**Comment by megoth** [comment]
We ended up releasing rdflib as v1.0.3 (https://github.com/linkeddata/rdflib.js/commit/7ea45781eea662ebe972ed2f1767c86339901d28), bringing rdflib into v1.
