### ISSUE TITLE
Error in v1.0.3

### ISSUE THREAD

**Issue by Vinnl** [linkeddata/rdflib.js#342]
The following error was reported [here](https://gitter.im/linkeddata/rdflib.js?at=5d5c1e77950718247717e691):

```
./node_modules/rdflib/src/updates-via.js
Attempted import error: 'namedNode' is not exported from './data-factory'.
```

The bug in question was introduced [here](https://github.com/linkeddata/rdflib.js/pull/335/files#r315792526). As mentioned there, the problem is:

> `namedNode` is not a named export of `data-factory` - instead, it offers a default export of an object with a property `namedNode`.

**Comment by RubenVerborgh** [comment]
Fixed in e7c5680122def0a2b1298fb5c7158203dd24c707.
