### ISSUE TITLE
Fetching JSON-LD does not appear to work

### ISSUE THREAD

**Issue by dantman** [linkeddata/rdflib.js#343]
Fetching a JSON-LD document does not appear to put anything into the store.

I tested this out with 1.0.4 by trying to fetch various urls with `nowOrWhenFetched` and dumping the store with toString when fetched.

I verified my test for fetching data worked by fetching Turtle (application/x-turtle) data. This worked, dumping a pile of data from Book.ttl into the store.
```js
var $rdf = require('rdflib');
var store = $rdf.graph();
var fetcher = new $rdf.Fetcher(store, 5000);
fetcher.nowOrWhenFetched('http://schema.org/Book.ttl', () => { console.log(store.toString()); });
```

Fetching RDF data failed, however that's fine because schema.org is incorrectly returned a application/xml content-type.
```js
var $rdf = require('rdflib');
var store = $rdf.graph();
var fetcher = new $rdf.Fetcher(store, 5000);
fetcher.nowOrWhenFetched('http://schema.org/Book.rdf', () => { console.log(store.toString()); });
```

But trying to fetch the JSON-LD version of the document also failed. This failure was not expected because the server correctly sends back a `application/ld+json; charset=utf-8` content-type.
```js
var $rdf = require('rdflib');
var store = $rdf.graph();
var fetcher = new $rdf.Fetcher(store, 5000);
fetcher.nowOrWhenFetched('http://schema.org/Book.jsonld', () => { console.log(store.toString()); });
```

**Comment by angelo-v** [comment]
Fixed in https://github.com/linkeddata/rdflib.js/pull/468

**Comment by bourgeoa** [comment]
@angelo-v #468 only soved the predicate part.
see PR #469 that should solve the predicate and object when using @type as a node type or a value type per JSON-LD specification https://json-ld.org/spec/latest/json-ld/#typed-values.
