### ISSUE TITLE
require XMLHtttRequest in camel case

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/rdflib.js#38]
if (typeof module != 'undefined' && module && module.exports) { //Node.js
            var XMLHttpRequest = require("XMLHttpRequest").XMLHttpRequest;
            return new XMLHttpRequest()
        }

https://github.com/linkeddata/rdflib.js/blob/master/util.js#L120

Is there any reason that this require is in camel case?  When running in node I get the following error:

    Error: Cannot find module 'XMLHttpRequest'

Lower case would appear to work fine, as per the docs.

https://www.npmjs.org/package/xmlhttprequest

    var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
    var xhr = new XMLHttpRequest();

I'd happily make the change here, but just wanted to know if there's anything that might break moving this to lowercase?

**Comment by dmitrizagidulin** [comment]
This issue has been fixed in a recent build. Thanks @melvincarvalho.
Closing.
