### ISSUE TITLE
Breaking change in JSON-LD parsing?

### ISSUE THREAD

**Issue by howarddierking** [linkeddata/rdflib.js#408]
Hi - apologies in advance if I missed this somewhere, but was there a breaking change introduced to how JSON-LD is parsed in one of the last versions. 

The following was working in `0.19.0` 

Test file
```
const explicit = `{
  "@context": { 
    "@base": "http://schema.howarddierking.com/",
    "@vocab": "http://schema.org/"
  },
  "@type": "Person",
  "@id": "/howard-dierking",
  "name": "Howard Dierking",
  "givenName": "Howard",
  "familyName": "Dierking",
  "url": "https://www.howarddierking.com"
}`;

describe('index', () => {
	describe('#getFirstName', () => {
		it('should return expected value for explicit triples', (done) => {
			R.pipeP(subject.graphFor, subject.getFirstName)(explicit)
			.then(actual => {
				actual.should.eql('Howard');
				done();
			});
		});
		
                // more tests ...
	})
})
```

Relevant src file
```
const jsonLd = 'application/ld+json';
const parseRdf = P.promisify(rdf.parse);

function graphFor(s){
	let g = rdf.graph();

	return parseRdf(s, g, null, jsonLd);
}
```

Under `1.1.0`, this code now fails because what looks to be zero items being loaded into the store.  Is there a known change here in rdflib (or the jsonld lib)?

**Comment by josephguillaume** [comment]
It looks like this issue is because the change to reduce code bloat in Oct 2019 https://github.com/linkeddata/rdflib.js/issues/349 did not convert `@type` to `rdf:type` (see comment on code: https://github.com/linkeddata/rdflib.js/commit/16daad7d68d805aa29e8e01bb4a16d77b28b6afe#r41313390), and errors were also accidentally suppressed (#435)

Here's a simpler test case (though note that parse is async for json-ld)
```
      g = $rdf.graph();
      const explicit = `{
        "@context": {
          "@base": "http://schema.howarddierking.com/",
          "@vocab": "http://schema.org/"
        },
        "@type": "Person",
        "@id": "/howard-dierking",
        "name": "Howard Dierking",
        "givenName": "Howard",
        "familyName": "Dierking",
        "url": "https://www.howarddierking.com"
      }`;
      $rdf.parse(explicit, g, null, "application/ld+json");
      g.statements
```
