### ISSUE TITLE
Non-HTTP fetch exception: TypeError: this.emit is not a function

### ISSUE THREAD

**Issue by michielbdejong** [linkeddata/rdflib.js#456]
thrown from https://github.com/linkeddata/rdflib.js/blob/master/src/fetcher.ts#L1139
seems to come from solid-auth-fetcher/src/AuthFetcher.ts:74

**Comment by michielbdejong** [comment]
Maybe rdflib is not binding the fetch function to the fetcher

**Comment by michielbdejong** [comment]
Ah fixed, I was doing
```js
rdf.fetcher(this.store, solidAuthFetcher) // Attach a web I/O module, store.fetcher
```
but I should be doing
```js
const options = {
  fetch: solidAuthFetcher.fetch.bind(solidAuthFetcher)
};
rdf.fetcher(this.store, options) // Attach a web I/O module, store.fetcher
```

**Comment by jeff-zucker** [comment]
Yep, I did the same mistake and found the same fix with solid-node-client/
