### ISSUE TITLE
Latest NPM package doesn't contain TypeScript types

### ISSUE THREAD

**Issue by sroze** [linkeddata/rdflib.js#457]
The latest package published to NPM does not contain the TypeScript types. Because [`npm build:types` works](https://github.com/linkeddata/rdflib.js/issues/442#issuecomment-731617196) my only theory is that the latest person we published didn't run this command. Good thing... 2.1.2 (75d1343) has not been pushed to NPM 👯 

@michielbdejong is this something you could help with? 🙏

**Comment by michielbdejong** [comment]
Thanks for the heads-up!
Ah, that's probably related then, because it will have successfully tagged the version, but then tried and failed to run `npm build` pre-publish.
/me looking.

**Comment by michielbdejong** [comment]
I published v2.1.3 now.
Can you try with that?
