### ISSUE TITLE
Rename default branch to 'main'

### ISSUE THREAD

**Issue by michielbdejong** [linkeddata/rdflib.js#475]
Can someone with access to https://github.com/linkeddata/rdflib.js/settings/branches change the default branch name from 'master' to 'main'?

I'm doing this for all repos in the Solid OS stack, but don't have access to this one.

**Comment by csarven** [comment]
May want to follow-up with the npm flow and dependencies.

Another follow-up is update the URLs in https://github.com/linkeddata/rdflib.js/search?q=https%3A%2F%2Fgithub.com%2Flinkeddata%2Frdflib.js%2Fblob%2Fmaster%2F and probably in other key repositories under solid.

**Comment by michielbdejong** [comment]
Done! :)
