### ISSUE TITLE
Fetcher fetches wrong URL

### ISSUE THREAD

**Issue by nicola** [linkeddata/rdflib.js#48]
This is my code

``` javascript
var TIMEOUT = 90000;
var g = $rdf.graph();
var f = $rdf.fetcher(g, TIMEOUT);
var followURI = "http://schema.rdfs.org/all.nt";
var SCHEMA = $rdf.Namespace('http://www.w3.org/2000/01/rdf-schema')
f.nowOrWhenFetched(followURI, undefined, function(ok, body){
  console.log(g.statementsMatching(undefined, SCHEMA("Class"), undefined));
})
```

Apparently I get an object g which is not the followURI I pass but this:

```
 thisURI: 'http://dig.csail.mit.edu/2005/ajar/ajaw/rdf/sources.js#SourceFetcher',
```

Am I doing something wrong? What is the idea of passing followURI if it will use thisURI?

**Comment by kezike** [comment]
I am having a similar issue to this, but a bit different. Particularly, when I try to fetch subfolders of my WebID, such as `/inbox` and `/public`, via `rdflib`'s `load` function, I am retrieving my profile card, as opposed to the content of these subfolders. Also, as a sanity check, I am able to fetch these subfolders with `curl` without a problem. Has anyone ever come across this problem?
