### ISSUE TITLE
kb fetcher.webOperations('GET', ...) returns falsly response.responseText undefined

### ISSUE THREAD

**Issue by bourgeoa** [linkeddata/rdflib.js#506]
from https://github.com/solid/source-pane/issues/17

rdflib.js in `kb.fetcher.webOperations()` is responsible of the problem.
`response.responseText` on some situation returns undefined.
Replacing by `await response.text()` returns correctly the body.

**Comment by timbl** [comment]
Interesting ... here is a debugger dump of the response object when this problem arises:
![image](https://user-images.githubusercontent.com/1254848/123398155-1f7f0f80-d59b-11eb-993a-5c1ba91bb332.png)

**Comment by timbl** [comment]
It is strange that the obejct does not have a `response.body()` getter which https://developer.mozilla.org/en-US/docs/Web/API/Response says it should, as the Response also mixes in:
![image](https://user-images.githubusercontent.com/1254848/123398766-ccf22300-d59b-11eb-9dc1-f5fa56be7ba3.png)

**Comment by bourgeoa** [comment]
This is not only a chrome bug only I got it also on firefox.
