### ISSUE TITLE
Installing from GitHub source will not include `lib`, `dist` and `esm` folders

### ISSUE THREAD

**Issue by RinkeHoekstra** [linkeddata/rdflib.js#559]
When installing rdflib from latest source, e.g. through GitHub, the `npm install` script does not build the package properly and does not create the `lib`, `dist` and `esm` folders.

**Comment by angelo-v** [comment]
`npm install` is not enough, you need to run `npm run build`, `npm run build:esm` and/or `npm run build:browser` to create those directories
