### ISSUE TITLE
Update jsonld >=6

### ISSUE THREAD

**Issue by bourgeoa** [linkeddata/rdflib.js#586]
See https://gitter.im/linkeddata/rdflib.js?at=6380e303326f06602c650c2d

**Comment by bourgeoa** [comment]
@pduchesne could you check rdflib@2.2.21-acff123a this is the result of PR #587

I updated to latest dependencies that allowed to resolve a few issues in code and typescript
A special issue with jsonld that do not support node 12 ans only node 14 latest.

**Comment by pduchesne** [comment]
Thx, it solves the problem reported above. Good for me.
