### ISSUE TITLE
Cannot serialize application/ld+json

### ISSUE THREAD

**Issue by bourgeoa** [linkeddata/rdflib.js#588]
```
Error: Serialize: Content-type application/json+ld not supported for data write.
```

**Comment by TallTed** [comment]
You've *probably* already noticed this, but the issue is so sparsely written, I can't be sure. So, I'll note -- the error refers to `application/`**`json+ld`** (which is a nonexistent media type), not to `application/`**`ld+json`** (as in your issue title). Maybe that helps speed the fix.
