### ISSUE TITLE
Add JSON-LD parser

### ISSUE THREAD

**Issue by timbl** [linkeddata/rdflib.js#59]
We need to be able to read JSON/LD as well as the other formats. Just adding this formally to the issue list now.   @martinmr has been working on this, possibly port from gold, possibly port from other JS implementation.

**Comment by akuckartz** [comment]
:+1:

**Comment by martinmr** [comment]
Issue has been resolved and version 0.2.3 includes support for serializing and parsing JSON-LD and n-quads.
