### ISSUE TITLE
Support for RDF-star?

### ISSUE THREAD

**Issue by benjaminaaron** [linkeddata/rdflib.js#606]
Are you supporting [RDF-star syntax](https://w3c.github.io/rdf-star/cg-spec/editors_draft.html) or are planning to? I tried adding a statement about a statement, but couldn't figure it out. Which might mean it's not possible yet?
If `rdflib.js` is not supporting this - do you know another JavaScript library that already has support for it?

**Comment by bourgeoa** [comment]
> Are you supporting [RDF-star syntax](https://w3c.github.io/rdf-star/cg-spec/editors_draft.html) or are planning to?

Nothing is planned actually

> If rdflib.js is not supporting this - do you know another JavaScript library that already has support for it?

You may look to https://github.com/linkeddata/rdflib.js/issues/601

**Comment by benjaminaaron** [comment]
Alright, I will, thanks @bourgeoa.
