### ISSUE TITLE
Remove console.log calls

### ISSUE THREAD

**Issue by timbl** [linkeddata/rdflib.js#610]
Particularly annoying are these two:

```
Internal error - fetchQueue exists file:///Users/timbl/Documents/Public/Archive/matrix.org/YjPbpwNkIIgPNhvxhg/index.ttl
*** Fetcher: pending fetchQueue deleted file:///Users/timbl/Documents/Public/Archive/matrix.org/YjPbpwNkIIgPNhvxhg/index.ttl
```
The fetchqueue logic should be rewritten eventully to use async/await, by the way, so this code is not so important to undersand

**Comment by bourgeoa** [comment]
> Particularly annoying are these two:

Was done https://github.com/linkeddata/rdflib.js/commit/32a22f20c613acc496710c28ba8519c72ea217f2
And published with rdflib@2.2.28
