### ISSUE TITLE
update https://github.com/linkeddata/rdflib.js/blob/main/Documentation/update-manager.md

### ISSUE THREAD

**Issue by bourgeoa** [linkeddata/rdflib.js#627]
@damooo @angelo-v 
Can you update https://github.com/linkeddata/rdflib.js/blob/main/Documentation/update-manager.md following :
- https://github.com/SolidOS/solidos/issues/185 N3-patch
- and subsequent closing of https://github.com/linkeddata/rdflib.js/issues/473

Does this imply that NSS could be able to use `Accept-patch` header https://github.com/nodeSolidServer/node-solid-server/issues/1683 ?

**Comment by angelo-v** [comment]
Accept header is already supported by rdflib for a while, but only with sparql update. Now it should work with n3 patch as well. I do not think that rdflib needs the ms-authore-via header anymore

**Comment by bourgeoa** [comment]
I don't think we can delete it for backward compatibility.

**Comment by angelo-v** [comment]
I do not mean to remove it from rdflib, I am just saying that rdflib would be fine if NSS removed it

**Comment by damooo** [comment]
> @damooo @angelo-v Can you update https://github.com/linkeddata/rdflib.js/blob/main/Documentation/update-manager.md following :

Created a PR #628 

> Does this imply that NSS could be able to use `Accept-patch` header [nodeSolidServer/node-solid-server#1683](https://github.com/nodeSolidServer/node-solid-server/issues/1683) ?

Yes, if NSS sends `accept-patch` header with "text/n3" being one of supported mimes, rdflib should send a `patch` request with content-type `text/n3`, with body encoding a solid-insert-delete-patch. rdflib hounoured sparql-update for accept-patch since much before.
