### ISSUE TITLE
Failed to install rdflib through npm

### ISSUE THREAD

**Issue by nicola** [linkeddata/rdflib.js#63]
I just tried the following:

```
$ npm install rdflib
|
> rdflib@0.2.0 postinstall /Users/mozilla/Proj/gits/ldnode/node_modules/rdflib
> make clean all

make: *** No rule to make target `clean'.  Stop.
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "rdflib"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! rdflib@0.2.0 postinstall: `make clean all`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the rdflib@0.2.0 postinstall script 'make clean all'.
npm ERR! This is most likely a problem with the rdflib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make clean all
npm ERR! You can get their info via:
npm ERR!     npm owner ls rdflib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mozilla/Proj/gits/ldnode/npm-debug.log
```

**Comment by martinmr** [comment]
At the moment I haven't updated rdflib on npm. Please use the github version. If you need to use rdflib, you can point npm to the github repository in your package.json.

**Comment by nicola** [comment]
or for reference I solved with the following

```
git clone https://github.com/linkeddata/rdflib.js
cd rdflib.js
npm link
```

and in any other project using rdflib,

```
npm link rdflib
```

For now I will leave this issue open, but not having the npm package working could be an issue for some!

**Comment by deiu** [comment]
It's actually an issue for everyone trying to install ldnode.

**Comment by nicola** [comment]
alright, let's ship this 0.2.1
(I don't have npm access!)

**Comment by martinmr** [comment]
Not yet. I still have to finish up support for JSON-LD (serialize works but I still have to test parse).

**Comment by nicola** [comment]
Perfect then! Although for future reference we should set up a set of rules for publishing on npm, some sort of continuous deployment, so that we always have the latest thing - that works :)

**Comment by nicola** [comment]
Any news on this?
Can we publish the new version?

**Comment by martinmr** [comment]
I think it's ready.

**Comment by martinmr** [comment]
Version 0.2.3 has been published and it's working. Ignore versions 0.2.1 and 0.2.2 since they worked on my machine but I didn't realized the makefile was not being included and caused make to fail. The solution was to remove the post install script since it's unnecessary.

**Comment by nicola** [comment]
Brilliant,
Thanks for this
