### ISSUE TITLE
Logging into inrupt.net gives "" alert and fails

### ISSUE THREAD

**Issue by timbl** [linkeddata/rdflib.js#639]
I try to log into inrupt.net with my inrupt.net id and I get an alert `Subject is not a subject type`

Looking at the code which throws it it it seems to be the code which adds and "outOfDate triple to the store,
``
kb.add(response, this.ns.link('outOfDate'), true as any, meta)
```
suggesting `response` is nill

**Comment by timbl** [comment]
<img width="987" alt="Screenshot 2024-02-27 at 21 19 01" src="https://github.com/linkeddata/rdflib.js/assets/1254848/7c472fd4-0303-4ad8-b7a7-57a5a88c3e72">

**Comment by angelo-v** [comment]
I am getting the same error when logging out

**Comment by angelo-v** [comment]
I am only experiencing it in Chrome, where I got some new CORS issues. The response might be null due to CORS blocking.

**Comment by bourgeoa** [comment]
I only got this issue with webID URL with fragment. Is it your case ?
