### ISSUE TITLE
rdflib fails to install on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by jamsden** [linkeddata/rdflib.js#77]
<pre>
jra-ibm-work:node_modules jamsden$ npm install rdflib

> rdflib@0.2.6 prepublish /Users/jamsden/Developer/node/node_modules/rdflib
> make clean all

make: *** No rule to make target `clean'.  Stop.

npm ERR! addLocalDirectory Could not pack /Users/jamsden/Developer/node/node_modules/rdflib to /Users/jamsden/.npm/rdflib/0.2.6/package.tgz
npm ERR! addLocal Could not install /Users/jamsden/Developer/node/node_modules/rdflib
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "rdflib"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! rdflib@0.2.6 prepublish: `make clean all`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the rdflib@0.2.6 prepublish script 'make clean all'.
npm ERR! This is most likely a problem with the rdflib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make clean all
npm ERR! You can get their info via:
npm ERR!     npm owner ls rdflib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamsden/Developer/node/node_modules/npm-debug.log
jra-ibm-work:node_modules jamsden$ npm install io
io@0.0.6 io
└── basic-promise@0.0.6
</pre>
node version: v0.12.7

**Comment by jamsden** [comment]
My fault, I was in the wrong directory.

**Comment by melvincarvalho** [comment]
Does it work now?

**Comment by jamsden** [comment]
Yes, everything is fine. Sorry for the distraction.
