### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/rdflib.js#79]
https://github.com/linkeddata/rdflib.js/blob/9e584e9ea0519bbac0d99ed1183dfcdaa6d7063d/web.js#L622

    if (document && document.location && $rdf.Fetcher.crossSiteProxyTemplate

triggers an error.  I tried changing it to 

    typeof(document !== undefined) 

but then document.location gave an error

        if (typeof(document) !== undefined && document.location && $rdf.Fetche
                                              ^
    ReferenceError: document is not defined
        at proxyIfNecessary (/usr/local/lib/node_modules/gitpay/node_modules/rdflib/dist/rdflib.js:24812:47)

any solution to this?

**Comment by timbl** [comment]
Should be fixed by #80   
(By the way never write typeof(document) always typeof document  -- it is a magic thing not a function.)

**Comment by timbl** [comment]
(Oooops I see trying it the parens are optional in fact - i was wrong)

**Comment by timbl** [comment]
Fixed now
