### ISSUE TITLE
Do we still need `rdflib-alpha.js`?

### ISSUE THREAD

**Issue by dmitrizagidulin** [linkeddata/rdflib.js#94]
Is it safe to remove the `dist/rdflib-alpha.js` Make step? It's identical to the main `rdflib.js` file:

```Make
dist/rdflib-alpha.js: $R module.js
	echo "(function(root, undef) {" > $@
	cat $R module.js >> $@
	date '+$$rdf.buildTime = "%Y-%m-%dT%H:%M:%S";'  >> $@
	echo "})(this);" >> $@

dist/rdflib.js: $R module.js
	echo "(function(root, undef) {" > $@
	cat $R module.js >> $@
	date '+$$rdf.buildTime = "%Y-%m-%dT%H:%M:%S";'  >> $@
	echo "})(this);" >> $@
```
Some net searching seems to indicate that it was possibly intended to include RDFa parsing originally? (Source: ["Maybe we should make a rdflib-alpha.js which does."](https://github.com/linkeddata/rdflib.js/issues/52)). In any case, it doesn't seem to be needed at the moment.

**Comment by deiu** [comment]
:+1: to remove that step.

**Comment by dmitrizagidulin** [comment]
Talked to @timbl yesterday, he gave the go-ahead to unify the three dist/ releases into one (and merge the RDFa parser into the main one, even though it's currently buggy).

**Comment by dmitrizagidulin** [comment]
Fixed in https://github.com/linkeddata/rdflib.js/issues/95, closing.
